"""
CoxM1-simulation-fast.py

Generated by Claude Code to speed up the simulation for several replicas and
efficiently save queue lengths at checkpoints.

M/M/1 queue with Cox (doubly-stochastic Poisson) arrivals.
Uses Numba JIT + parallel replicas for speed, and streams results
to a compressed HDF5 file (int16) for compact multi-checkpoint storage.

Reading results later:
    import h5py, numpy as np
    with h5py.File('Data/....h5', 'r') as f:
        cps = f['queue_lengths'].attrs['checkpoints']  # checkpoint times
        X   = f['queue_lengths'][:]                    # shape (replicas, n_checkpoints)
        X_t3 = f['queue_lengths'][:, 2]               # all replicas at the 3rd checkpoint
"""

import numpy as np
import numba
import os
import h5py
import time
import pandas as pd


# ── Parameters ────────────────────────────────────────────────────────────────

Z_initial_value = 20
service_rate = 30.0
#   5  → a=0.3, b=80,  service_rate=10 or 30
#   80 → a=0.3, b=80,  service_rate=100
#   70 → a=0.3, b=150, service_rate=100

v = 2
#   1 → dynamic UB: recomputed each call from the remaining rate path
#   2 → fixed global UB = 1.1 * max(Z)  [recommended]

if Z_initial_value == 5:
    a, b         = 0.3, 80
    z_csv        = os.path.join('./Data', 'initial_value_5_samples_500.csv')
elif Z_initial_value == 20:
    a, b         = 0.3, 80
    z_csv        = os.path.join('./Data', 'initial_value_20_samples_500_a_0.3_b_20_delta_1.csv')
elif Z_initial_value == 80:
    a, b         = 0.3, 80
    z_csv        = os.path.join('./Data', 'initial_value_80_samples_500.csv')
elif Z_initial_value == 70:
    a, b         = 0.3, 150
    z_csv        = os.path.join('./Data', 'initial_value_70_samples_500_a_0.3_b_150.csv')
else:
    raise ValueError("Z_initial_value must be 5, 70, or 80")

time_horizon = 10.0                               # simulation horizon
checkpoints  = np.arange(1.0, time_horizon + 1.0, 1.0)  # [1, 2, ..., 10]
replicas     = 10**8                              # total replicas
batch_size   = 10**6                              # replicas per batch (≈ 20 MB int16 RAM per batch)


# ── Load arrival-rate process Z ───────────────────────────────────────────────

Z_data    = pd.read_csv(z_csv)
Z         = Z_data[['time', 'value']].to_numpy()
Z_vals    = np.ascontiguousarray(Z[:, 1], dtype=np.float64)
Z_n       = len(Z_vals)
step_size = float(Z[1, 0] - Z[0, 0])   # time between samples (e.g. 0.02)

if v == 1:
    # Dynamic UB: will be recomputed inside each arrival-generation call.
    # We pass the full 2-D Z array so the function can slice the future path.
    Z_full = np.ascontiguousarray(Z, dtype=np.float64)
    UB_global = 1.1 * np.max(Z_vals)   # used only for warm-up call
elif v == 2:
    Z_full    = Z_vals                  # not used in v=2, but keep for warm-up
    UB_global = 1.1 * np.max(Z_vals)


# ── Numba JIT functions ───────────────────────────────────────────────────────

@numba.njit(cache=True)
def _next_arrival_v2(clock, Z_vals, Z_n, step_size, T, UB):
    """
    Thinning algorithm with fixed upper bound UB.
    Returns next Cox arrival time after `clock`, or 3*T if none before T.
    """
    if clock >= T:
        return 3.0 * T
    arr_time = clock
    while True:
        arr_time += np.random.exponential(1.0 / UB)
        if arr_time >= T:
            return 3.0 * T
        u   = np.random.uniform(0.0, UB)
        idx = int(arr_time / step_size)
        if idx >= Z_n:
            return 3.0 * T
        if Z_vals[idx] > u:
            return arr_time


@numba.njit(cache=True)
def _next_arrival_v1(clock, Z_full, Z_n, step_size, T):
    """
    Thinning algorithm with dynamic UB recomputed from the remaining path.
    Returns next Cox arrival time after `clock`, or 3*T if none before T.
    """
    if clock >= T:
        return 3.0 * T
    idx_clock = int(clock / step_size)
    if idx_clock >= Z_n:
        return 3.0 * T
    # UB from current position to end of horizon
    UB = 0.0
    for i in range(idx_clock, Z_n):
        if Z_full[i, 1] > UB:
            UB = Z_full[i, 1]
    UB *= 1.1

    arr_time = clock
    while True:
        arr_time += np.random.exponential(1.0 / UB)
        if arr_time >= T:
            return 3.0 * T
        u   = np.random.uniform(0.0, UB)
        idx = int(arr_time / step_size)
        if idx >= Z_n:
            return 3.0 * T
        if Z_full[idx, 1] > u:
            return arr_time


@numba.njit(parallel=True, cache=True)
def simulate_batch_v2(n, Z_vals, Z_n, step_size, T, service_rate, checkpoints, UB):
    """
    Run `n` independent replicas in parallel (fixed-UB thinning).
    Returns int16 array of shape (n, n_checkpoints) with sampled queue lengths.
    """
    n_cp = len(checkpoints)
    X    = np.empty((n, n_cp), dtype=np.int16)

    for r in numba.prange(n):
        current_time = 0.0
        q      = 0
        t_dep  = 3.0 * T
        t_arr  = _next_arrival_v2(0.0, Z_vals, Z_n, step_size, T, UB)
        cp_idx = 0

        while current_time < T:
            if t_arr <= t_dep:
                # arrival event
                current_time = t_arr
                q           += 1
                t_arr = _next_arrival_v2(current_time, Z_vals, Z_n, step_size, T, UB)
                if q == 1:
                    t_dep = current_time + np.random.exponential(1.0 / service_rate)
            else:
                # departure event
                current_time = t_dep
                q           -= 1
                if q == 0:
                    t_dep = 3.0 * T
                else:
                    t_dep = current_time + np.random.exponential(1.0 / service_rate)

            # Record any checkpoints that the next event skips over
            next_evt = min(t_arr, t_dep)
            while cp_idx < n_cp and next_evt >= checkpoints[cp_idx]:
                X[r, cp_idx] = q
                cp_idx += 1
            if cp_idx == n_cp:
                break

        # Fill any checkpoints not yet reached (queue drained, no arrivals left)
        while cp_idx < n_cp:
            X[r, cp_idx] = q
            cp_idx += 1

    return X


@numba.njit(parallel=True, cache=True)
def simulate_batch_v1(n, Z_full, Z_n, step_size, T, service_rate, checkpoints):
    """
    Run `n` independent replicas in parallel (dynamic-UB thinning).
    Returns int16 array of shape (n, n_checkpoints) with sampled queue lengths.
    """
    n_cp = len(checkpoints)
    X    = np.empty((n, n_cp), dtype=np.int16)

    for r in numba.prange(n):
        current_time = 0.0
        q      = 0
        t_dep  = 3.0 * T
        t_arr  = _next_arrival_v1(0.0, Z_full, Z_n, step_size, T)
        cp_idx = 0

        while current_time < T:
            if t_arr <= t_dep:
                current_time = t_arr
                q           += 1
                t_arr = _next_arrival_v1(current_time, Z_full, Z_n, step_size, T)
                if q == 1:
                    t_dep = current_time + np.random.exponential(1.0 / service_rate)
            else:
                current_time = t_dep
                q           -= 1
                if q == 0:
                    t_dep = 3.0 * T
                else:
                    t_dep = current_time + np.random.exponential(1.0 / service_rate)

            next_evt = min(t_arr, t_dep)
            while cp_idx < n_cp and next_evt >= checkpoints[cp_idx]:
                X[r, cp_idx] = q
                cp_idx += 1
            if cp_idx == n_cp:
                break

        while cp_idx < n_cp:
            X[r, cp_idx] = q
            cp_idx += 1

    return X


# ── Warm up Numba (JIT compile before timing) ─────────────────────────────────

print("Compiling JIT functions ...", flush=True)
_warm = 4   # tiny batch just to trigger compilation
if v == 2:
    simulate_batch_v2(_warm, Z_vals, Z_n, step_size, time_horizon,
                      service_rate, checkpoints, UB_global)
else:
    simulate_batch_v1(_warm, Z_full, Z_n, step_size, time_horizon,
                      service_rate, checkpoints)
print("Done.\n", flush=True)


# ── Output file ───────────────────────────────────────────────────────────────

out_name = (f"CoxM1_Z0{Z_initial_value}_serv{int(service_rate)}"
            f"_T{int(time_horizon)}_v{v}.h5")
out_path = os.path.join('./Data (2026)', out_name)

n_cp      = len(checkpoints)
n_batches = (replicas + batch_size - 1) // batch_size
chunk_rows = min(65536, batch_size)   # HDF5 chunk: ~1.3 MB each at 10 checkpoints


# ── Run simulation, streaming batches to HDF5 ────────────────────────────────

with h5py.File(out_path, 'w') as f:
    ds = f.create_dataset(
        'queue_lengths',
        shape     = (0, n_cp),
        maxshape  = (None, n_cp),
        dtype     = 'int16',
        chunks    = (chunk_rows, n_cp),
        compression      = 'gzip',
        compression_opts = 4,
        shuffle   = True,   # byte-shuffle before gzip → better ratio for integers
    )
    # Metadata stored as HDF5 attributes
    ds.attrs['checkpoints']     = checkpoints
    ds.attrs['service_rate']    = service_rate
    ds.attrs['time_horizon']    = time_horizon
    ds.attrs['Z_initial_value'] = Z_initial_value
    ds.attrs['replicas']        = replicas
    ds.attrs['v']               = v
    ds.attrs['UB']              = UB_global

    wall_start = time.time()
    total_done = 0

    for b in range(n_batches):
        n_this = min(batch_size, replicas - total_done)

        t_sim0 = time.time()
        if v == 2:
            X_batch = simulate_batch_v2(n_this, Z_vals, Z_n, step_size,
                                        time_horizon, service_rate,
                                        checkpoints, UB_global)
        else:
            X_batch = simulate_batch_v1(n_this, Z_full, Z_n, step_size,
                                        time_horizon, service_rate,
                                        checkpoints)
        t_sim1 = time.time()

        # Append batch to extensible HDF5 dataset
        old = ds.shape[0]
        ds.resize(old + n_this, axis=0)
        ds[old : old + n_this] = X_batch

        total_done += n_this
        elapsed   = time.time() - wall_start
        remaining = elapsed / total_done * (replicas - total_done)
        print(
            f"  Batch {b+1:>3}/{n_batches}  |"
            f"  {total_done/replicas*100:5.1f}%  |"
            f"  sim {t_sim1-t_sim0:5.1f}s  |"
            f"  elapsed {elapsed/60:5.1f}m  |"
            f"  ETA {remaining/60:5.1f}m",
            flush=True,
        )

total_wall = time.time() - wall_start
print(f"\nFinished. Total wall time: {total_wall/60:.1f} min")
print(f"Saved to:  {out_path}")
